// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  traderName: __t.string().name("trader_name"),
  traderStyle: __t.string().name("trader_style"),
  rank: __t.u64(),
  portfolioValueCents: __t.u64().name("portfolio_value_cents"),
  cashCents: __t.u64().name("cash_cents"),
  lastReasoning: __t.string().name("last_reasoning"),
  lastActionSummary: __t.string().name("last_action_summary"),
  lastDecisionSource: __t.string().name("last_decision_source"),
  updatedAt: __t.timestamp().name("updated_at"),
});
