// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  dayIndex: __t.u64().name("day_index"),
  bestFundSymbol: __t.string().name("best_fund_symbol"),
  worstFundSymbol: __t.string().name("worst_fund_symbol"),
  bestFundReturnBps: __t.i64().name("best_fund_return_bps"),
  worstFundReturnBps: __t.i64().name("worst_fund_return_bps"),
  topPlayerName: __t.string().name("top_player_name"),
  topPlayerValueCents: __t.u64().name("top_player_value_cents"),
  createdAt: __t.timestamp().name("created_at"),
});
