// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  fundSymbol: __t.string().name("fund_symbol"),
  fundName: __t.string().name("fund_name"),
  symbol: __t.string(),
  name: __t.string(),
  shares: __t.u64(),
  priceCents: __t.u64().name("price_cents"),
  dayOpenPriceCents: __t.u64().name("day_open_price_cents"),
  valueCents: __t.u64().name("value_cents"),
  weightBps: __t.u64().name("weight_bps"),
  updatedAt: __t.timestamp().name("updated_at"),
});
