// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  dayIndex: __t.u64().name("day_index"),
  phase: __t.string(),
  currentGameMinute: __t.u64().name("current_game_minute"),
  currentGameTimeLabel: __t.string().name("current_game_time_label"),
  secondsUntilClose: __t.u64().name("seconds_until_close"),
  secondsUntilNextDay: __t.u64().name("seconds_until_next_day"),
  tradesAllowed: __t.bool().name("trades_allowed"),
  predictionsAllowed: __t.bool().name("predictions_allowed"),
});
