// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  symbol: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  riskProfile: __t.string().name("risk_profile"),
  totalShares: __t.u64().name("total_shares"),
  availableShares: __t.u64().name("available_shares"),
  navCents: __t.u64().name("nav_cents"),
  priceCents: __t.u64().name("price_cents"),
  previousPriceCents: __t.u64().name("previous_price_cents"),
  dayOpenPriceCents: __t.u64().name("day_open_price_cents"),
  tradingDayIndex: __t.u64().name("trading_day_index"),
  updatedAt: __t.timestamp().name("updated_at"),
});
