// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  trader: __t.identity(),
  symbol: __t.string(),
  side: __t.string(),
  shares: __t.u64(),
  priceCents: __t.u64().name("price_cents"),
  totalCents: __t.u64().name("total_cents"),
  createdAt: __t.timestamp().name("created_at"),
});
