// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  stockSymbol: __t.string().name("stock_symbol"),
  stockName: __t.string().name("stock_name"),
  splitRatio: __t.u64().name("split_ratio"),
  executeAtMicros: __t.i64().name("execute_at_micros"),
  announced: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
});
