// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  owner: __t.identity(),
  balanceCents: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const Holding = __t.object("Holding", {
  id: __t.u64(),
  owner: __t.identity(),
  symbol: __t.string(),
  shares: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Holding = __Infer<typeof Holding>;

export const Leaderboard = __t.object("Leaderboard", {});
export type Leaderboard = __Infer<typeof Leaderboard>;

export const LeaderboardRow = __t.object("LeaderboardRow", {
  owner: __t.identity(),
  name: __t.string(),
  balanceCents: __t.u64(),
  estimatedPortfolioValueCents: __t.u64(),
});
export type LeaderboardRow = __Infer<typeof LeaderboardRow>;

export const LlmConfig = __t.object("LlmConfig", {
  owner: __t.identity(),
  provider: __t.string(),
  apiKey: __t.string(),
  model: __t.string(),
  systemPrompt: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type LlmConfig = __Infer<typeof LlmConfig>;

export const LlmConfigStatus = __t.object("LlmConfigStatus", {
  configured: __t.bool(),
  provider: __t.option(__t.string()),
  model: __t.option(__t.string()),
  systemPrompt: __t.option(__t.string()),
});
export type LlmConfigStatus = __Infer<typeof LlmConfigStatus>;

export const MarketNews = __t.object("MarketNews", {
  id: __t.u64(),
  headline: __t.string(),
  body: __t.string(),
  symbol: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  isAiGenerated: __t.bool(),
});
export type MarketNews = __Infer<typeof MarketNews>;

export const MyAccount = __t.object("MyAccount", {});
export type MyAccount = __Infer<typeof MyAccount>;

export const MyHoldings = __t.object("MyHoldings", {});
export type MyHoldings = __Infer<typeof MyHoldings>;

export const MyTrades = __t.object("MyTrades", {});
export type MyTrades = __Infer<typeof MyTrades>;

export const PlayerDirectory = __t.object("PlayerDirectory", {
  owner: __t.identity(),
  name: __t.string(),
  nameKey: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PlayerDirectory = __Infer<typeof PlayerDirectory>;

export const RecentTrade = __t.object("RecentTrade", {
  id: __t.u64(),
  trader: __t.identity(),
  symbol: __t.string(),
  side: __t.string(),
  shares: __t.u64(),
  priceCents: __t.u64(),
  totalCents: __t.u64(),
  createdAt: __t.timestamp(),
});
export type RecentTrade = __Infer<typeof RecentTrade>;

export const Stock = __t.object("Stock", {
  symbol: __t.string(),
  name: __t.string(),
  priceCents: __t.u64(),
  previousPriceCents: __t.u64(),
  volume: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Stock = __Infer<typeof Stock>;

export const TradeLedger = __t.object("TradeLedger", {
  id: __t.u64(),
  owner: __t.identity(),
  symbol: __t.string(),
  side: __t.string(),
  shares: __t.u64(),
  priceCents: __t.u64(),
  totalCents: __t.u64(),
  createdAt: __t.timestamp(),
});
export type TradeLedger = __Infer<typeof TradeLedger>;

