// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  owner: __t.identity(),
  balanceCents: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const AiConnectionStatus = __t.object("AiConnectionStatus", {
  ok: __t.bool(),
  message: __t.string(),
  provider: __t.option(__t.string()),
  model: __t.option(__t.string()),
});
export type AiConnectionStatus = __Infer<typeof AiConnectionStatus>;

export const AiMarketNewsTimer = __t.object("AiMarketNewsTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AiMarketNewsTimer = __Infer<typeof AiMarketNewsTimer>;

export const AiNewsStatus = __t.object("AiNewsStatus", {});
export type AiNewsStatus = __Infer<typeof AiNewsStatus>;

export const AiNewsStatusRow = __t.object("AiNewsStatusRow", {
  active: __t.bool(),
  paused: __t.bool(),
  lastError: __t.string(),
});
export type AiNewsStatusRow = __Infer<typeof AiNewsStatusRow>;

export const AiSchedulerState = __t.object("AiSchedulerState", {
  key: __t.string(),
  paused: __t.bool(),
  lastError: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AiSchedulerState = __Infer<typeof AiSchedulerState>;

export const AiTraderApexTimer = __t.object("AiTraderApexTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AiTraderApexTimer = __Infer<typeof AiTraderApexTimer>;

export const AiTraderLog = __t.object("AiTraderLog", {});
export type AiTraderLog = __Infer<typeof AiTraderLog>;

export const AiTraderLogRow = __t.object("AiTraderLogRow", {
  id: __t.u64(),
  traderName: __t.string(),
  traderStyle: __t.string(),
  symbol: __t.string(),
  side: __t.string(),
  shares: __t.u64(),
  priceCents: __t.u64(),
  totalCents: __t.u64(),
  createdAt: __t.timestamp(),
});
export type AiTraderLogRow = __Infer<typeof AiTraderLogRow>;

export const AiTraderMemory = __t.object("AiTraderMemory", {
  owner: __t.identity(),
  lastReasoning: __t.string(),
  lastActionSummary: __t.string(),
  lastDecisionSource: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AiTraderMemory = __Infer<typeof AiTraderMemory>;

export const AiTraderMindRow = __t.object("AiTraderMindRow", {
  traderName: __t.string(),
  traderStyle: __t.string(),
  rank: __t.u64(),
  portfolioValueCents: __t.u64(),
  cashCents: __t.u64(),
  lastReasoning: __t.string(),
  lastActionSummary: __t.string(),
  lastDecisionSource: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AiTraderMindRow = __Infer<typeof AiTraderMindRow>;

export const AiTraderMinds = __t.object("AiTraderMinds", {});
export type AiTraderMinds = __Infer<typeof AiTraderMinds>;

export const AiTraderNovaTimer = __t.object("AiTraderNovaTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AiTraderNovaTimer = __Infer<typeof AiTraderNovaTimer>;

export const AiTraderPulseTimer = __t.object("AiTraderPulseTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AiTraderPulseTimer = __Infer<typeof AiTraderPulseTimer>;

export const DailyPrediction = __t.object("DailyPrediction", {
  id: __t.u64(),
  owner: __t.identity(),
  dayIndex: __t.u64(),
  bestFundSymbol: __t.string(),
  worstFundSymbol: __t.string(),
  submittedAt: __t.timestamp(),
  settledAt: __t.option(__t.timestamp()),
  actualBestFundSymbol: __t.option(__t.string()),
  actualWorstFundSymbol: __t.option(__t.string()),
  bestCorrect: __t.bool(),
  worstCorrect: __t.bool(),
  bonusCents: __t.u64(),
});
export type DailyPrediction = __Infer<typeof DailyPrediction>;

export const DailyPredictionViewRow = __t.object("DailyPredictionViewRow", {
  dayIndex: __t.u64(),
  bestFundSymbol: __t.string(),
  worstFundSymbol: __t.string(),
  submittedAt: __t.timestamp(),
  settledAt: __t.option(__t.timestamp()),
  actualBestFundSymbol: __t.option(__t.string()),
  actualWorstFundSymbol: __t.option(__t.string()),
  bestCorrect: __t.bool(),
  worstCorrect: __t.bool(),
  bonusCents: __t.u64(),
});
export type DailyPredictionViewRow = __Infer<typeof DailyPredictionViewRow>;

export const DaySummary = __t.object("DaySummary", {
  id: __t.u64(),
  dayIndex: __t.u64(),
  bestFundSymbol: __t.string(),
  worstFundSymbol: __t.string(),
  bestFundReturnBps: __t.i64(),
  worstFundReturnBps: __t.i64(),
  topPlayerName: __t.string(),
  topPlayerValueCents: __t.u64(),
  createdAt: __t.timestamp(),
});
export type DaySummary = __Infer<typeof DaySummary>;

export const Fund = __t.object("Fund", {
  symbol: __t.string(),
  name: __t.string(),
  managerIdentityHex: __t.string(),
  kind: __t.string(),
  riskProfile: __t.string(),
  totalShares: __t.u64(),
  availableShares: __t.u64(),
  navCents: __t.u64(),
  priceCents: __t.u64(),
  previousPriceCents: __t.u64(),
  dayOpenPriceCents: __t.u64(),
  tradingDayIndex: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Fund = __Infer<typeof Fund>;

export const FundConstituentRow = __t.object("FundConstituentRow", {
  fundSymbol: __t.string(),
  fundName: __t.string(),
  symbol: __t.string(),
  name: __t.string(),
  shares: __t.u64(),
  priceCents: __t.u64(),
  dayOpenPriceCents: __t.u64(),
  valueCents: __t.u64(),
  weightBps: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type FundConstituentRow = __Infer<typeof FundConstituentRow>;

export const FundConstituents = __t.object("FundConstituents", {});
export type FundConstituents = __Infer<typeof FundConstituents>;

export const FundHolding = __t.object("FundHolding", {
  id: __t.u64(),
  owner: __t.identity(),
  symbol: __t.string(),
  shares: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type FundHolding = __Infer<typeof FundHolding>;

export const FundMarketRow = __t.object("FundMarketRow", {
  symbol: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  riskProfile: __t.string(),
  totalShares: __t.u64(),
  availableShares: __t.u64(),
  navCents: __t.u64(),
  priceCents: __t.u64(),
  previousPriceCents: __t.u64(),
  dayOpenPriceCents: __t.u64(),
  tradingDayIndex: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type FundMarketRow = __Infer<typeof FundMarketRow>;

export const FundTradeLedger = __t.object("FundTradeLedger", {
  id: __t.u64(),
  owner: __t.identity(),
  symbol: __t.string(),
  side: __t.string(),
  shares: __t.u64(),
  priceCents: __t.u64(),
  totalCents: __t.u64(),
  createdAt: __t.timestamp(),
});
export type FundTradeLedger = __Infer<typeof FundTradeLedger>;

export const GameClockTimer = __t.object("GameClockTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GameClockTimer = __Infer<typeof GameClockTimer>;

export const GameDay = __t.object("GameDay", {
  id: __t.string(),
  dayIndex: __t.u64(),
  openedAtMicros: __t.i64(),
  phase: __t.string(),
  currentGameMinute: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type GameDay = __Infer<typeof GameDay>;

export const GitHubLoginResult = __t.object("GitHubLoginResult", {
  ok: __t.bool(),
  message: __t.string(),
  username: __t.option(__t.string()),
  avatarUrl: __t.option(__t.string()),
});
export type GitHubLoginResult = __Infer<typeof GitHubLoginResult>;

export const GitHubOAuthStatus = __t.object("GitHubOAuthStatus", {
  configured: __t.bool(),
  clientId: __t.option(__t.string()),
});
export type GitHubOAuthStatus = __Infer<typeof GitHubOAuthStatus>;

export const GithubOauthConfig = __t.object("GithubOauthConfig", {
  id: __t.string(),
  clientId: __t.string(),
  clientSecret: __t.string(),
  updatedAt: __t.timestamp(),
});
export type GithubOauthConfig = __Infer<typeof GithubOauthConfig>;

export const GithubProfile = __t.object("GithubProfile", {
  owner: __t.identity(),
  githubUsername: __t.string(),
  githubAvatarUrl: __t.string(),
  updatedAt: __t.timestamp(),
});
export type GithubProfile = __Infer<typeof GithubProfile>;

export const GlobalAiConfig = __t.object("GlobalAiConfig", {
  id: __t.string(),
  provider: __t.string(),
  apiKey: __t.string(),
  model: __t.string(),
  systemPrompt: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type GlobalAiConfig = __Infer<typeof GlobalAiConfig>;

export const GlobalAiConfigStatus = __t.object("GlobalAiConfigStatus", {
  configured: __t.bool(),
  provider: __t.option(__t.string()),
  model: __t.option(__t.string()),
  systemPrompt: __t.option(__t.string()),
});
export type GlobalAiConfigStatus = __Infer<typeof GlobalAiConfigStatus>;

export const Holding = __t.object("Holding", {
  id: __t.u64(),
  owner: __t.identity(),
  symbol: __t.string(),
  shares: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Holding = __Infer<typeof Holding>;

export const KeyArticle = __t.object("KeyArticle", {
  id: __t.u64(),
  dayIndex: __t.u64(),
  symbol: __t.string(),
  sentiment: __t.string(),
  headline: __t.string(),
  body: __t.string(),
  shockBps: __t.i64(),
  applied: __t.bool(),
  createdAt: __t.timestamp(),
});
export type KeyArticle = __Infer<typeof KeyArticle>;

export const LatestDaySummary = __t.object("LatestDaySummary", {});
export type LatestDaySummary = __Infer<typeof LatestDaySummary>;

export const Leaderboard = __t.object("Leaderboard", {});
export type Leaderboard = __Infer<typeof Leaderboard>;

export const LeaderboardRow = __t.object("LeaderboardRow", {
  owner: __t.identity(),
  name: __t.string(),
  balanceCents: __t.u64(),
  estimatedPortfolioValueCents: __t.u64(),
});
export type LeaderboardRow = __Infer<typeof LeaderboardRow>;

export const LlmConfig = __t.object("LlmConfig", {
  owner: __t.identity(),
  provider: __t.string(),
  apiKey: __t.string(),
  model: __t.string(),
  systemPrompt: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type LlmConfig = __Infer<typeof LlmConfig>;

export const LlmConfigStatus = __t.object("LlmConfigStatus", {
  configured: __t.bool(),
  provider: __t.option(__t.string()),
  model: __t.option(__t.string()),
  systemPrompt: __t.option(__t.string()),
});
export type LlmConfigStatus = __Infer<typeof LlmConfigStatus>;

export const ManagerTradingPlan = __t.object("ManagerTradingPlan", {
  id: __t.u64(),
  manager: __t.identity(),
  fundSymbol: __t.string(),
  dayIndex: __t.u64(),
  thesis: __t.string(),
  riskPosture: __t.string(),
  source: __t.string(),
  createdAt: __t.timestamp(),
});
export type ManagerTradingPlan = __Infer<typeof ManagerTradingPlan>;

export const ManagerTradingPlanStep = __t.object("ManagerTradingPlanStep", {
  id: __t.u64(),
  planId: __t.u64(),
  manager: __t.identity(),
  fundSymbol: __t.string(),
  dayIndex: __t.u64(),
  gameMinute: __t.u64(),
  action: __t.string(),
  symbol: __t.string(),
  shares: __t.u64(),
  reasoning: __t.string(),
  executed: __t.bool(),
  executedAt: __t.option(__t.timestamp()),
});
export type ManagerTradingPlanStep = __Infer<typeof ManagerTradingPlanStep>;

export const MarketActivityTimer = __t.object("MarketActivityTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MarketActivityTimer = __Infer<typeof MarketActivityTimer>;

export const MarketClock = __t.object("MarketClock", {});
export type MarketClock = __Infer<typeof MarketClock>;

export const MarketClockRow = __t.object("MarketClockRow", {
  dayIndex: __t.u64(),
  phase: __t.string(),
  currentGameMinute: __t.u64(),
  currentGameTimeLabel: __t.string(),
  secondsUntilClose: __t.u64(),
  secondsUntilNextDay: __t.u64(),
  tradesAllowed: __t.bool(),
  predictionsAllowed: __t.bool(),
});
export type MarketClockRow = __Infer<typeof MarketClockRow>;

export const MarketFunds = __t.object("MarketFunds", {});
export type MarketFunds = __Infer<typeof MarketFunds>;

export const MarketNews = __t.object("MarketNews", {
  id: __t.u64(),
  headline: __t.string(),
  body: __t.string(),
  symbol: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  isAiGenerated: __t.bool(),
});
export type MarketNews = __Infer<typeof MarketNews>;

export const MarketStocks = __t.object("MarketStocks", {});
export type MarketStocks = __Infer<typeof MarketStocks>;

export const MyAccount = __t.object("MyAccount", {});
export type MyAccount = __Infer<typeof MyAccount>;

export const MyDailyPrediction = __t.object("MyDailyPrediction", {});
export type MyDailyPrediction = __Infer<typeof MyDailyPrediction>;

export const MyFundHoldings = __t.object("MyFundHoldings", {});
export type MyFundHoldings = __Infer<typeof MyFundHoldings>;

export const MyFundTrades = __t.object("MyFundTrades", {});
export type MyFundTrades = __Infer<typeof MyFundTrades>;

export const MyGithubProfile = __t.object("MyGithubProfile", {});
export type MyGithubProfile = __Infer<typeof MyGithubProfile>;

export const MyHoldings = __t.object("MyHoldings", {});
export type MyHoldings = __Infer<typeof MyHoldings>;

export const MyPlayer = __t.object("MyPlayer", {});
export type MyPlayer = __Infer<typeof MyPlayer>;

export const MyPortfolioHistory = __t.object("MyPortfolioHistory", {});
export type MyPortfolioHistory = __Infer<typeof MyPortfolioHistory>;

export const MyTrades = __t.object("MyTrades", {});
export type MyTrades = __Infer<typeof MyTrades>;

export const PlayerDirectory = __t.object("PlayerDirectory", {
  owner: __t.identity(),
  name: __t.string(),
  nameKey: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PlayerDirectory = __Infer<typeof PlayerDirectory>;

export const PortfolioHistoryPoint = __t.object("PortfolioHistoryPoint", {
  hourStartMicros: __t.i64(),
  portfolioValueCents: __t.u64(),
});
export type PortfolioHistoryPoint = __Infer<typeof PortfolioHistoryPoint>;

export const PortfolioSnapshot = __t.object("PortfolioSnapshot", {
  id: __t.u64(),
  owner: __t.identity(),
  hourStartMicros: __t.i64(),
  portfolioValueCents: __t.u64(),
  recordedAt: __t.timestamp(),
});
export type PortfolioSnapshot = __Infer<typeof PortfolioSnapshot>;

export const PredictionLeaderboard = __t.object("PredictionLeaderboard", {});
export type PredictionLeaderboard = __Infer<typeof PredictionLeaderboard>;

export const PredictionLeaderboardRow = __t.object("PredictionLeaderboardRow", {
  name: __t.string(),
  totalPredictions: __t.u64(),
  correctPredictions: __t.u64(),
  accuracyPct: __t.u64(),
  totalBonusCents: __t.u64(),
});
export type PredictionLeaderboardRow = __Infer<typeof PredictionLeaderboardRow>;

export const PredictionResults = __t.object("PredictionResults", {});
export type PredictionResults = __Infer<typeof PredictionResults>;

export const RecentMarketNews = __t.object("RecentMarketNews", {});
export type RecentMarketNews = __Infer<typeof RecentMarketNews>;

export const RecentTrade = __t.object("RecentTrade", {
  id: __t.u64(),
  trader: __t.identity(),
  symbol: __t.string(),
  side: __t.string(),
  shares: __t.u64(),
  priceCents: __t.u64(),
  totalCents: __t.u64(),
  createdAt: __t.timestamp(),
});
export type RecentTrade = __Infer<typeof RecentTrade>;

export const Stock = __t.object("Stock", {
  symbol: __t.string(),
  name: __t.string(),
  priceCents: __t.u64(),
  previousPriceCents: __t.u64(),
  dayOpenPriceCents: __t.u64(),
  tradingDayIndex: __t.u64(),
  volume: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Stock = __Infer<typeof Stock>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

export const TradeLedger = __t.object("TradeLedger", {
  id: __t.u64(),
  owner: __t.identity(),
  symbol: __t.string(),
  side: __t.string(),
  shares: __t.u64(),
  priceCents: __t.u64(),
  totalCents: __t.u64(),
  createdAt: __t.timestamp(),
});
export type TradeLedger = __Infer<typeof TradeLedger>;

