// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as GetLlmConfigStatusProcedure from "../get_llm_config_status_procedure";

export type GetLlmConfigStatusArgs = __Infer<typeof GetLlmConfigStatusProcedure.params>;
export type GetLlmConfigStatusResult = __Infer<typeof GetLlmConfigStatusProcedure.returnType>;

