// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as GenerateDemoNewsProcedure from "../generate_demo_news_procedure";
import * as GetGlobalAiConfigStatusProcedure from "../get_global_ai_config_status_procedure";
import * as GetLlmConfigStatusProcedure from "../get_llm_config_status_procedure";
import * as TestGlobalAiConnectionProcedure from "../test_global_ai_connection_procedure";

export type GenerateDemoNewsArgs = __Infer<typeof GenerateDemoNewsProcedure.params>;
export type GenerateDemoNewsResult = __Infer<typeof GenerateDemoNewsProcedure.returnType>;
export type GetGlobalAiConfigStatusArgs = __Infer<typeof GetGlobalAiConfigStatusProcedure.params>;
export type GetGlobalAiConfigStatusResult = __Infer<typeof GetGlobalAiConfigStatusProcedure.returnType>;
export type GetLlmConfigStatusArgs = __Infer<typeof GetLlmConfigStatusProcedure.params>;
export type GetLlmConfigStatusResult = __Infer<typeof GetLlmConfigStatusProcedure.returnType>;
export type TestGlobalAiConnectionArgs = __Infer<typeof TestGlobalAiConnectionProcedure.params>;
export type TestGlobalAiConnectionResult = __Infer<typeof TestGlobalAiConnectionProcedure.returnType>;

