// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BuyFundReducer from "../buy_fund_reducer";
import BuyStockReducer from "../buy_stock_reducer";
import SeedDemoPlayersReducer from "../seed_demo_players_reducer";
import SeedMarketReducer from "../seed_market_reducer";
import SellFundReducer from "../sell_fund_reducer";
import SellStockReducer from "../sell_stock_reducer";
import SetGithubOauthConfigReducer from "../set_github_oauth_config_reducer";
import SetGlobalAiConfigReducer from "../set_global_ai_config_reducer";
import SetLlmConfigReducer from "../set_llm_config_reducer";
import SetNameReducer from "../set_name_reducer";
import SubmitPredictionReducer from "../submit_prediction_reducer";

export type BuyFundParams = __Infer<typeof BuyFundReducer>;
export type BuyStockParams = __Infer<typeof BuyStockReducer>;
export type SeedDemoPlayersParams = __Infer<typeof SeedDemoPlayersReducer>;
export type SeedMarketParams = __Infer<typeof SeedMarketReducer>;
export type SellFundParams = __Infer<typeof SellFundReducer>;
export type SellStockParams = __Infer<typeof SellStockReducer>;
export type SetGithubOauthConfigParams = __Infer<typeof SetGithubOauthConfigReducer>;
export type SetGlobalAiConfigParams = __Infer<typeof SetGlobalAiConfigReducer>;
export type SetLlmConfigParams = __Infer<typeof SetLlmConfigReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SubmitPredictionParams = __Infer<typeof SubmitPredictionReducer>;

