// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BuyStockReducer from "../buy_stock_reducer";
import SeedMarketReducer from "../seed_market_reducer";
import SellStockReducer from "../sell_stock_reducer";
import SetGlobalAiConfigReducer from "../set_global_ai_config_reducer";
import SetLlmConfigReducer from "../set_llm_config_reducer";
import SetNameReducer from "../set_name_reducer";

export type BuyStockParams = __Infer<typeof BuyStockReducer>;
export type SeedMarketParams = __Infer<typeof SeedMarketReducer>;
export type SellStockParams = __Infer<typeof SellStockReducer>;
export type SetGlobalAiConfigParams = __Infer<typeof SetGlobalAiConfigReducer>;
export type SetLlmConfigParams = __Infer<typeof SetLlmConfigReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;

